import Head from 'next/head'
import { sanityClient } from '../sanity'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Services from '../components/Services'
import flowerIcon from '.././public/icons/flower-4.png'
import rocksIcon from '.././public/icons/rocks.png'
import bambooIcon from '.././public/icons/bamboo icon.png'
import candleIcon from '.././public/icons/candle icon.png'
import oilsImg from '.././public/oils img.jpeg'
import flowerIcon2 from '.././public/icons/flower-3.png'
import teaIcon from '.././public/icons/Tea icon.png'
import boneIcon from '.././public/icons/bone icon.png'
import bodyMassageIcon from '.././public/icons/body massage icon.png'
import faceMaskIcon from '.././public/icons/face mask icon.png'
import geothermicMassageIcon from '.././public/icons/geothermic icon.png'
import fullBodyMassageIcon from '.././public/icons/full body massage icon.png'
import saunaIcon from '.././public/icons/sauna icon.png'
import makeupIcon from '.././public/icons/makeup and massage.png'
import Link from 'next/link'
import Menu from '../components/Menu'
import { Post } from '.././typings'


export interface Props {
  posts: [Post];
}


export function getCategory(post){
 let category = post.categories.map(category => category.title).toString()
  return category
}



export default function Home({ posts }: Props) {


  //console.log(typeof posts.map(post => post.categories.map(category => category.title)).toString())

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full">
        <Header />
        <Hero />

        <div className='relative grid grid-cols-1 xsm:grid-cols-2 md:grid-cols-4 gap-3 items-stretch place-content-stretch justify-items-stretch justify-evenly mx-auto px-[10px] pt-[10px]'>
          {posts.map((post) => {
            if (getCategory(post) == "service" || getCategory(post) == "service-image") 
            {
              let category = getCategory(post)

              return (
                  <Services post={post} />
              )
            }
            else {
              return
            }
          }
          )}


        </div>

        {/*<Services posts={posts} />*/}

        <section className="relative py-20 m-auto px-[5%]">
          <div className='flex-1 max-w-[1200px] m-auto text-center'>
            <div className="m-auto max-w-[95%] md:max-w-[65%] mb-[60px]">
              <div className="w-[70px] mx-auto md:mb-5">
                <Image src={flowerIcon} alt="header" width={511} height={420} />
              </div>
              <h2 className='my-[10px] font-syne font-bold text-[30px] leading-8 md:text-[39px] md:leading-[42px]'>
                The healing effect of aromatherapy on your mind & body
              </h2>
            </div>



            <div className='grid grid-flow-row xsm:grid-cols-2 base:grid-cols-3 items-stretch justify-items-stretch content-evenly justify-evenly'>

              <div className='flex flex-col pt-0 md:px-[34px] pb-10 items-center justify-between'>
                <div className="inline-block w-[50px] max-w-full xsm:pb-3 h-auto">
                  <Image src={rocksIcon} alt="rocks" width={500} height={559} />
                </div>
                <div className='flex-1'>
                  <h3 className="font-syne font-bold text-[19px] leading-[22px] mt-10 mb-[10px]">
                    Stone spa
                  </h3>
                  <p className="font-playfair text-[17px] text-dim-gray leading-[23px] mb-[10px]">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  </p>
                  <Link href="/">
                    <a className="font-syne font-bold text-sm leading-[17px] mt-5 underline">Learn More</a>
                  </Link>
                </div>
              </div>


              <div className='flex flex-col pt-0 md:px-[34px] pb-10 items-center justify-between'>
                <div className="inline-block w-[50px] max-w-full h-auto">
                  <Image src={bambooIcon} alt="rocks" width={800} height={1097} />
                </div>
                <div className='flex-1'>
                  <h3 className="font-syne font-bold text-[19px] leading-[22px] mt-10 mb-[10px]">
                    Winter Ritual
                  </h3>
                  <p className="font-playfair text-[17px] text-dim-gray leading-[23px] mb-[10px]">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  </p>
                  <Link href="/">
                    <a className="font-syne font-bold text-sm leading-[17px] mt-5 underline">Learn More</a>
                  </Link>
                </div>
              </div>

              <div className='flex flex-col pt-0 md:px-[34px] pb-10 items-center justify-between'>
                <div className="inline-block w-[50px] max-w-full h-auto">
                  <Image src={candleIcon} alt="rocks" width={500} height={713} />
                </div>

                <div className='flex-1'>
                  <h3 className="font-syne font-bold text-[19px] leading-[22px] mt-10 mb-[10px]">
                    Candle Message
                  </h3>

                  <p className="font-playfair text-[17px] text-dim-gray leading-[23px] mb-[10px]">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  </p>

                  <Link href="/">
                    <a className="font-syne font-bold text-sm leading-[17px] mt-5 underline">Learn More</a>
                  </Link>
                </div>
              </div>
            </div>

            <div className='grid  md:grid-cols-2 items-center justify-items-stretch content-evenly justify-evenly gap-[100px] mt-20'>
              <div className="w-auto h-auto max-w-full">
                <Image src={oilsImg} alt="header" width={2000} height={2080} />
              </div>

              <div className="max-w-[80%] mx-auto my-0 text-left">
                <div className="w-[70px] max-w-full mb-[-30px]">
                  <Image src={flowerIcon2} alt="header" width={502} height={370} />
                </div>

                <h2 className='font-syne my-10 font-bold text-[39px] leading-[42px]'>
                  Experience <br />& knowledge gained over 10 years.
                </h2>

                <p className="mb-[10px] font-playfair text-[17px] leading-[23px] text-dim-gray">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.
                  <br />
                  <br />
                  Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.
                </p>

                <button className="mt-[50px] relative bg-burlywood mb-4 md:mb-0 py-3 px-8 md:px-5 rounded-md text-sm font-syne font-bold">Make Reservation</button>
              </div>
            </div>







            {/* PRICING GRID */}
            <div className='grid md:grid-rows-4 md:grid-cols-2 gap-y-8 md:gap-x-[70px] items-stretch justify-items-stretch content-evenly content-justify-evenly pt-14  md:pt-28'>
              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={teaIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Aroma Therapy</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $55
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>

              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={boneIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Backbone Therapy</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $107
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>


              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={bodyMassageIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Body Massage</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $36
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>

              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={faceMaskIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Face Masks</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $41
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>

              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={geothermicMassageIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Geothermal spa</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne italic text-[30px] leading-[30px] mr-[5px]">
                        $42
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>



              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={fullBodyMassageIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Full Body Massage</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $14
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>

              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={saunaIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Sauna Relax</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $55
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>

              <div className='flex justify-start items-center text-start'>

                <div className="w-[44px] h-[50px] max-w-full mr-5">
                  <Image src={makeupIcon} alt="header" width={512} height={512} />
                </div>

                <div className="w-[100%]">
                  {/*price top*/}
                  <div className="flex items-end justify-start pb-[10px] w-{100%]">
                    <h4 className='font-syne font-bold text-base leading-5 my-0 xsm:mr-5 whitespace-nowrap'>Makeup & Massage</h4>
                    <div className="hidden xsm:block w-[100%] h-[1px] bg-line-gray"></div>

                    <div className="flex items-end justify-start flex-shrink-0 flex-grow-0 ml-5">
                      <p className="font-playfair italic text-[15px] text-dim-gray leading-[23px] mb-0 mr-[5px]">
                        from
                      </p>
                      <p className="font-syne text-[30px] leading-[30px] mr-[5px]">
                        $19
                      </p>
                    </div>
                  </div>
                  <p className="font-playfair text-[17px] leading-[23px] text-dim-gray">
                    Lorem ispum dolor sit amet
                  </p>
                </div>


              </div>
            </div>


          </div>


        </section>

      </div>

    </div>
  )
}

export const getServerSideProps = async () => {
  const query = `
  *[_type == "service-post" ] {
    _id,
    categories[]->{
    title
  },
  postNumber,
  
    title,
  description,
  mainImage,
    slug
   }`;


  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts
    }
  }
} 